#include <stdio.h>
#include <stdlib.h>
#include "kalman.h"
#include "est_apogee.h"


typedef struct {
    int safety;
    int mtroff;
} sw_stuff;

sw_stuff RocketSw(double mu[2], double t, int sw_safety);

int main(){
    double mu_prior[2];
    double S_prior[2][2];
    double unused;
    double y[2];
    double y_good[2];
    double t;
    double delta_t;
    int sw;
    int jj;
    
    y_good[0] = 0;
    y_good[1] = 1;
    
    FILE *fileid;
    FILE *fileod;
    fileid=fopen("data/kalmantestdata.csv","r");
    if (!fileid) {
      perror("data/kalmantestdata.csv");
      exit(1);
    }
    fileod=fopen("data/kalmantestresults.dat","w");
    if (!fileod) {
      perror("data/kalmantestresults.csv");
      exit(1);
    }

    FILE *gendata = fopen("test_data.c", "w");
    fprintf(gendata, "// Fake data for testing.  Generated by test-linux\n");
    fprintf(gendata, "// Manual modification discouraged.\n");
    fprintf(gendata, "#include \"test_data.h\"\n");
    fprintf(gendata, "static const test_data_t _test_data[] = {\n");

    kf_data_t new_hv;
    sw_stuff sw_data; 
    for (jj=1; jj<10000; jj++){
        if (feof(fileid)){
            break;
        }
        
        fscanf(fileid, "%lf," ,&(t));
        fscanf(fileid, "%lf," ,&(delta_t));
        fscanf(fileid, "%lf," ,&(y[0]));
        fscanf(fileid, "%lf," ,&(y[1]));       

        fprintf(gendata, "    {%d, %lf, %lf},\n", (jj-1)*(100), y[0], y[1]);
        //set initial values correctly
        if (t <= 0.1){
            mu_prior[0] = 0;
            mu_prior[1] = 0.0;
            S_prior[0][0] = 0;
            S_prior[0][1] = 0;
            S_prior[1][0] = 0;
            S_prior[1][1] = 0;
            sw_data.safety = 0;
        }
        else{
            mu_prior[0] = new_hv.mu[0];
            mu_prior[1] = new_hv.mu[1];
            S_prior[0][0] = new_hv.S[0][0];
            S_prior[0][1] = new_hv.S[0][1];
            S_prior[1][0] = new_hv.S[1][0];
            S_prior[1][1] = new_hv.S[1][1];
        }
        fscanf(fileid, "%lf," ,&(unused));
        fscanf(fileid, "%lf," ,&(unused));
        fscanf(fileid, "%lf," ,&(unused));
        fscanf(fileid, "%lf," ,&(unused));
        fscanf(fileid, "%lf," ,&(unused));
        fscanf(fileid, "%lf," ,&(unused));
        fscanf(fileid, "%i\n" ,&(sw));
       
        //update_kalman(mu_prior, S_prior, y, y_good, t, delta_t, sw);
        update_press(y[1], t*1000, sw);
        new_hv = kalman_state();
        double apogee = est_apogee(new_hv.mu, t);

        printf ("kf h = %lf kf_v = %lf apogee = %lf\n", 
            new_hv.mu[0], new_hv.mu[1], apogee);
        //fprintf(fileod, "%lf    %lf\n", t,new_hv.mu[0]);
        fprintf(fileod, "%lf, %lf, %lf, %lf, %lf\n", 
                t,y[0],y[1],new_hv.mu[0],new_hv.mu[1]);
     }
     fclose(fileod);

     fprintf(gendata, "    {-1, 0, 0}\n");
     fprintf(gendata, "};\n");
     fprintf(gendata, "const test_data_t * test_data = _test_data;\n");
     fprintf(gendata, "\n");
     fclose(gendata);
     //printf ("Hello World, here's mu_prior. \n%lf \n%lf \n" , mu_prior[0], mu_prior[1]);

     return 0;
}

