/******************************************************************************
 * test_data.h
 * Copyright 2011 Iain Peet
 *
 * Header defining type, data generated by test-linux
 ******************************************************************************
 * This program is distributed under the of the GNU Lesser Public License. 
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>
 *****************************************************************************/

#ifndef TEST_DATA_H_
#define TEST_DATA_H_

typedef struct {
    int t;
    float gps_alt;
    float press_alt;
} test_data_t;

const test_data_t * test_data;

#endif //TEST_DATA_H_
